### ISSUE TITLE
CWP grid 5x5

### ISSUE THREAD

**Issue by manuchassot** [fdiwg/fdi-codelists#12]
The grid "cwp:cwp-grid-map-5deg_x_5deg_erased" includes one field more (grid_area) than the other "erased" grids (1x1, 10x10 and 20x20 ) available from https://www.fao.org/fishery/geoserver/wfs. Would be ideal if all the grids had the same structure. I also wonder if of a layer including all grids at the same time (including smaller resolutions) could be made available to facilitate the use of the data,
Cheers

**Comment by eblondel** [comment]
For the grid with all resolutions, i'll investigate it
