### ISSUE TITLE
CWP "erased" grids

### ISSUE THREAD

**Issue by manuchassot** [fdiwg/fdi-codelists#13]
I noted that the WFS layers "cwp:cwp-grid-map-1deg_x_1deg_erased", "cwp:cwp-grid-map-10deg_x_10deg_erased", cwp:cwp-grid-map-20deg_x_20deg_erased" and "cwp:cwp-grid-map-30deg_x_30deg_erased" have **one more field (gml_id.1)** than "cwp:cwp-grid-map-5deg_x_5deg_erased". I also wonder if the label gml_id in this guy should be renamed to avoid duplication,

**Comment by eblondel** [comment]
the "gml_id" should be removed as well from there.
