### ISSUE TITLE
Code list for countries

### ISSUE THREAD

**Issue by manuchassot** [fdiwg/fdi-codelists#27]
My request to get a mapping between fishing fleets and countries actually calls for the addition of a **standard code list for countries**, including territories (NOCS?)

This would be very useful.

**Comment by eblondel** [comment]
Isn't it covered by https://github.com/fdiwg/fdi-codelists/blob/main/global/cwp/cl_flagstate_iso3.csv ?

**Comment by manuchassot** [comment]
Yes

**Comment by eblondel** [comment]
We could rename the file. This was inherited from FIRMS GTA where we called it initially `flagstate`, to then switch to the concept of `fishing_fleet`

**Comment by manuchassot** [comment]
Thanks Emmanuel. Would also be very useful to have a mapping
between fishing fleets and countries.

**Comment by eblondel** [comment]
but we have it :-) https://github.com/fdiwg/fdi-mappings/blob/main/global/firms/gta/codelist_mapping_fishingfleet_firms_flag_fao_cwp.csv

**Comment by manuchassot** [comment]
Sorry. Need to check before posting issues...
