### ISSUE TITLE
Incomplete mapping between GTA fleets and countries?

### ISSUE THREAD

**Issue by manuchassot** [fdiwg/fdi-codelists#29]
In the mapping file https://raw.githubusercontent.com/fdiwg/fdi-mappings/main/global/firms/gta/codelist_mapping_fishingfleet_firms_flag_fao_cwp.csv, there is no mapping for the following 4 fleets: (1) DDR, (2) EUR, (3) FRAT, and (4) GBRT. I would recommend to map the 4 country codes with (1) EUR, (2) DEU, (3) FRA and (4) GBR.

**Comment by eblondel** [comment]
can you submit a pull request to add them?

**Comment by manuchassot** [comment]
Done.

**Comment by eblondel** [comment]
don't see anything :-) did you push it?

**Comment by eblondel** [comment]
Ok i see sorry it's on https://github.com/fdi-mappings
