### ISSUE TITLE
FIRMS fishing fleets

### ISSUE THREAD

**Issue by manuchassot** [fdiwg/fdi-codelists#7]
The [DSD](https://docs.google.com/document/d/1NnrrbuQGisUmyojinJrL_NvM2JpRzpAdB0uMIbZoea8/edit) states in the column TARGET VALUES that "If not defined in strata use “ALL”. I suspect this should be explicitly included in the code list

**Comment by eblondel** [comment]
Actually, if this is not defined in data structure, this should be left empty, this means the information is not necessary. It's related to whether this information is mandatory or optional. In case it would be optional, column is provided, by we authorized NA value. If it is mandatory, column is provided, but we expect to have a fishing fleet, so "ALL" is excluded.
The document should be modified.
